{"name": "test_verify_successful_login_with_valid_credentials", "status": "failed", "statusDetails": {"message": "AssertionError: El login falló. No se redirigió exactamente a la página de cuenta.\nassert 'https://b1h2...w.com/account' == 'https://b1h2...fypreview.com'\n  \n  Skipping 44 identical leading characters in diff, use -v to show\n  - preview.com\n  + preview.com/account", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"d4cac6754a162547a40774ebce3dfb77\")>\n\n    def test_verify_successful_login_with_valid_credentials(driver):\n        # Create instance of LoginPage\n        login_page = LoginPage(driver)\n        #login\n        login_page.login(TestData.EMAIL, TestData.PASSWORD)\n        #time.sleep(20)\n>       assert driver.current_url == TestData.ACCOUNT_URL , \"El login falló. No se redirigió exactamente a la página de cuenta.\"\nE       AssertionError: El login falló. No se redirigió exactamente a la página de cuenta.\nE       assert 'https://b1h2...w.com/account' == 'https://b1h2...fypreview.com'\nE         \nE         Skipping 44 identical leading characters in diff, use -v to show\nE         - preview.com\nE         + preview.com/account\n\ntests\\test_login.py:14: AssertionError"}, "start": 1726248422779, "stop": 1726248428293, "uuid": "2c6ea815-83fd-4ee9-98c5-56e9b93d2fee", "historyId": "8e3e24edfb781c66ebd6f83bd232dec8", "testCaseId": "8e3e24edfb781c66ebd6f83bd232dec8", "fullName": "tests.test_login#test_verify_successful_login_with_valid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "Laptop-Diego"}, {"name": "thread", "value": "20112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}